In [2]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

!pip install mnist
import mnist

In [3]:
X = mnist.train_images().reshape(60000, 28 * 28)
y = mnist.train_labels()

tree = DecisionTreeClassifier(random_state=17)

depth_params = [x + 10 for x in range(10)]
tree_params = {'max_depth': depth_params}

tree_grid = GridSearchCV(tree, tree_params, cv=5, n_jobs=-1, verbose=True)

tree_grid.fit(X, y)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:  5.4min
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:  6.0min finished


GridSearchCV(cv=5, error_score=nan,
             estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort='deprecated',
                                              random_state=17,
                                              splitter='best'),
             iid='deprecated', n_jobs=-1,
             param_grid={'max_depth': [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]},
 

In [3]:
print('max_depth: {}'.format(tree_grid.best_params_['max_depth']))
print('accuracy: {}'.format(tree_grid.best_score_))

tree = DecisionTreeClassifier(max_depth=tree_grid.best_params_['max_depth'], random_state=17)

tree.fit(X, y)

y_pred = tree.predict(mnist.test_images().reshape(10000, 28 * 28))
y_true = mnist.test_labels()

print('accuracy: {}'.format(accuracy_score(y_pred, y_true)))

print('confusion matrix:')
print(confusion_matrix(y_true, y_pred))

print(classification_report(y_true, y_pred, digits=3))



max_depth: 15
accuracy: 0.8705499999999999
accuracy: 0.8836
confusion matrix:
[[ 924    1    9    6    6    8    6    2   12    6]
 [   3 1096   10    3    3    4    8    5    3    0]
 [  11   15  891   26   14   14   11   24   18    8]
 [  12    6   33  863    6   40    4   11   20   15]
 [   6    4    7    8  866    8   15   10   18   40]
 [  14    9    6   34    8  752   22    6   26   15]
 [  15    5   15    8   22   23  847    1   18    4]
 [   3   14   22   14    9    3    2  939    6   16]
 [  11    6   25   39   21   33   17    6  776   40]
 [  13    4    7   20   37    7    6   11   22  882]]
              precision    recall  f1-score   support

           0      0.913     0.943     0.928       980
           1      0.945     0.966     0.955      1135
           2      0.869     0.863     0.866      1032
           3      0.845     0.854     0.850      1010
           4      0.873     0.882     0.877       982
           5      0.843     0.843     0.843       892
           6